#!/bin/bash
set -e

function logStatus() { # as green text
    echo -e "\033[32m$1\033[0m"
}
function logError() { # as red text
    echo -e "\033[31m$1\033[0m"
}

DST=${1:-"linux64"}
DST=$(realpath "${DST}")
mkdir -p "${DST}" "${DST}/lib" "${DST}/include"

# Compiler + C++ runtime, passed by mamafile.py so x264/x265/FFmpeg match the rest of the
# build. Defaults keep direct invocation working. mama uses -stdlib=libc++ for clang, so the
# C++ libx265 must be built the same way or it won't link into a libc++ krattcam.
CC_BIN=${2:-gcc}
CXX_BIN=${3:-g++}
STDLIB=${4:-libstdc++}          # libstdc++ (gcc) or libc++ (clang)
if [ "${STDLIB}" = "libc++" ]; then
    CXX_STDLIB_FLAG="-stdlib=libc++"
    CXX_RUNTIME_LIBS="-lc++ -lc++abi"   # x265's C++ deps for downstream/FFmpeg link tests
else
    CXX_STDLIB_FLAG=""
    CXX_RUNTIME_LIBS="-lstdc++"
fi

logStatus "Building inside: ${DST} (cc=${CC_BIN} cxx=${CXX_BIN} stdlib=${STDLIB})"
#sudo apt-get install -y nasm libdrm-dev libbz2-dev cmake

###################################################
# Build x264 from source as a static library
###################################################
if [ ! -f "${DST}/lib/libx264.a" ]; then
    logStatus "Building x264 from source..."
    if [[ ! -f "${DST}/x264/configure" ]]; then
        rm -rf "${DST}/x264"
        git clone -q --depth 1 https://code.videolan.org/videolan/x264.git "${DST}/x264"
    fi
    pushd "${DST}/x264"
    CC="${CC_BIN}" ./configure --prefix="${DST}" \
        --enable-static \
        --enable-pic \
        --disable-cli
    make -j$(nproc) 2>&1 || [ -f libx264.a ] || { logError "x264 build failed"; exit 1; }
    make install
    popd
fi

###################################################
# Build x265 from source as a static library
###################################################
if [ ! -f "${DST}/lib/libx265.a" ]; then
    logStatus "Building x265 from source..."
    if [ ! -f "${DST}/x265/CMakeLists.txt" ]; then
        rm -rf "${DST}/x265"
        git clone -q --depth 1 https://bitbucket.org/multicoreware/x265_git.git "${DST}/x265"
    fi
    pushd "${DST}/x265/build/linux"
    # ENABLE_LIBNUMA=OFF: x265 otherwise auto-links libnuma when libnuma-dev is present,
    # leaving numa_* refs the downstream krattcam link doesn't provide (and the prebuilt
    # gcc package has no numa either — keep source builds consistent with it).
    cmake ../../source \
        -DCMAKE_INSTALL_PREFIX="${DST}" \
        -DCMAKE_C_COMPILER="${CC_BIN}" \
        -DCMAKE_CXX_COMPILER="${CXX_BIN}" \
        -DCMAKE_CXX_FLAGS="${CXX_STDLIB_FLAG}" \
        -DENABLE_SHARED=OFF \
        -DENABLE_CLI=OFF \
        -DENABLE_LIBNUMA=OFF \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    make -j$(nproc)
    make install
    popd
fi

# x265's CMake often installs no pkg-config file, so synthesize one when missing.
# Kept outside the build guard so a stale/incorrect .pc can be regenerated by just
# deleting it — no need to rebuild x265. FFmpeg's configure needs two things here:
#   1. Version = the real X265_BUILD number (in x265_config.h) to satisfy its
#      `x265 >= NN` pkg-config gate; a placeholder like 0.0 fails detection.
#   2. libx265 is C++, so the link test needs the C++ runtime: -lstdc++ for gcc,
#      -lc++ -lc++abi for clang/libc++. Wrong runtime => "x265 not found using pkg-config".
if [ -f "${DST}/lib/libx265.a" ] && [ ! -f "${DST}/lib/pkgconfig/x265.pc" ]; then
    mkdir -p "${DST}/lib/pkgconfig"
    X265BUILD=$(grep -rhoP '#define\s+X265_BUILD\s+\K[0-9]+' "${DST}/include/x265_config.h" "${DST}/include/x265.h" 2>/dev/null | head -1)
    : "${X265BUILD:=68}"  # fallback: minimum that satisfies FFmpeg's `x265 >= 68`
    cat > "${DST}/lib/pkgconfig/x265.pc" <<EOF
prefix=${DST}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: x265
Description: H.265/HEVC video encoder
Version: ${X265BUILD}
Libs: -L\${libdir} -lx265 ${CXX_RUNTIME_LIBS} -lm -lpthread -ldl
Libs.private: ${CXX_RUNTIME_LIBS} -lm -lpthread -ldl
Cflags: -I\${includedir}
EOF
fi

###################################################
# Build FFmpeg with statically linked x264/x265
###################################################
if [ ! -d "${DST}/FFmpeg-linux64" ] || [ ! -f "${DST}/FFmpeg-linux64/configure" ]; then
    rm -rf "${DST}/FFmpeg-linux64"
    git clone -q --branch release/8.0 --depth 1 https://github.com/FFmpeg/FFmpeg.git "${DST}/FFmpeg-linux64"
fi

pushd "${DST}/FFmpeg-linux64"

logStatus "Configure Linux 64-bit"
export PKG_CONFIG_PATH="${DST}/lib/pkgconfig:${PKG_CONFIG_PATH}"
# use TERM=dumb for avoiding CI failure
TERM=dumb ./configure --prefix="${DST}" \
    --cc="${CC_BIN}" \
    --cxx="${CXX_BIN}" \
    --disable-programs \
    --disable-doc \
    --disable-debug \
    --enable-static \
    --disable-shared \
    --enable-asm \
    --enable-gpl \
    --enable-nonfree \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libdrm \
    --disable-sndio \
    --disable-alsa \
    --extra-cflags="-I${DST}/include" \
    --extra-ldflags="-L${DST}/lib ${CXX_STDLIB_FLAG}"

# Build and install
logStatus "Starting build..."
make -j$(nproc) || { logError "BUILD FAILED"; exit 1; }

logStatus "Installing to ${DST} ..."
make install
logStatus "Done."

popd

# delete all symlinks in the lib folder so we have cleaner packaging
find "${DST}/lib" -type l -delete

# rename .so.62.11.100 to .so.62 for correct linkage
# and .so.6.1.100 to .so.6 for correct linkage
for lib in "${DST}/lib/lib"*".so."*; do
    base=$(basename "$lib")
    if [[ $base =~ (lib.*\.so\.[0-9]+) ]]; then
        newname="${BASH_REMATCH[1]}"
        echo "Renaming $base to $newname"
        mv "$lib" "${DST}/lib/${newname}"
    fi
done
